2021/08/05 11:54:38 [error] 32#32: *350 FastCGI sent in stderr: "PHP message: 2021-08-05T11:54:38+00:00 [critical] Uncaught Exception: Invalid firewall "main": user provider "users_in_memory" not found" while reading upstream, client: 172.21.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/08/10 12:19:05 [error] 30#30: *640 FastCGI sent in stderr: "PHP message: 2021-08-10T12:19:05+00:00 [critical] Uncaught Error: syntax error, unexpected ')'" while reading upstream, client: 172.21.0.1, server: localhost, request: "POST /user/new HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost", referrer: "http://localhost/user/new"
2021/08/10 12:48:33 [error] 30#30: *844 FastCGI sent in stderr: "PHP message: 2021-08-10T12:48:33+00:00 [critical] Uncaught Error: syntax error, unexpected ']'" while reading upstream, client: 172.21.0.1, server: localhost, request: "GET /companies/new HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost", referrer: "http://localhost/companies/"
2021/08/11 13:13:04 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/08/11 13:14:35 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/08/11 13:15:02 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/08/11 13:15:27 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/08/11 13:15:31 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/08/11 13:15:33 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/08/11 13:15:35 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/08/11 14:53:09 [warn] 32#32: *175 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /processes HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/08/12 15:00:11 [error] 32#32: *2170 FastCGI sent in stderr: "PHP message: 2021-08-12T15:00:11+00:00 [critical] Uncaught Error: syntax error, unexpected token ")"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /edit/1 HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/13 07:21:54 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/08/13 07:21:54 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/08/13 07:21:56 [error] 33#33: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/08/13 07:21:56 [error] 33#33: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/08/13 14:12:07 [error] 31#31: *1691 FastCGI sent in stderr: "PHP message: 2021-08-13T14:12:07+00:00 [critical] Uncaught Exception: Unrecognized option "0" under "security.access_control.4". Available options are "allow_if", "host", "ips", "methods", "path", "port", "requires_channel", "roles"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /logout HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/13 14:12:26 [error] 31#31: *1691 FastCGI sent in stderr: "PHP message: 2021-08-13T14:12:26+00:00 [critical] Uncaught Exception: Unrecognized option "0" under "security.access_control.4". Available options are "allow_if", "host", "ips", "methods", "path", "port", "requires_channel", "roles"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /logout HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/16 07:25:39 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/08/16 07:25:39 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/08/16 07:25:40 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/08/16 07:25:41 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/08/16 07:25:43 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/08/16 07:25:43 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/08/16 10:04:54 [error] 33#33: *916 FastCGI sent in stderr: "PHP message: 2021-08-16T10:04:54+00:00 [critical] Uncaught Exception: Unrecognized option "true," under "security.firewalls.main.switch_user". Available options are "parameter", "provider", "role"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /user HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/08/16 12:07:48 [warn] 33#33: *1037 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /logout HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/16 12:10:05 [warn] 33#33: *1040 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/2/00/0000000002 while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /logout HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/16 12:11:11 [warn] 33#33: *1043 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/3/00/0000000003 while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /logout HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/16 12:11:43 [warn] 33#33: *1046 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/4/00/0000000004 while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /logout HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/16 12:12:00 [warn] 33#33: *1049 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/5/00/0000000005 while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /logout HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/16 12:14:02 [warn] 33#33: *1058 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/6/00/0000000006 while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /logout HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/16 12:14:57 [warn] 33#33: *1061 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/7/00/0000000007 while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /logout HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/16 14:34:52 [error] 33#33: *1409 FastCGI sent in stderr: "PHP message: 2021-08-16T14:34:52+00:00 [critical] Uncaught Error: syntax error, unexpected token ";", expecting ")"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/08/16 14:34:57 [error] 33#33: *1409 FastCGI sent in stderr: "PHP message: 2021-08-16T14:34:57+00:00 [critical] Uncaught Error: syntax error, unexpected token ";", expecting ")"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/08/18 07:48:59 [error] 32#32: *160 FastCGI sent in stderr: "PHP message: 2021-08-18T07:48:59+00:00 [critical] Uncaught Error: Invalid numeric literal" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/18 08:10:44 [error] 32#32: *242 FastCGI sent in stderr: "PHP message: 2021-08-18T08:10:44+00:00 [critical] Uncaught Error: syntax error, unexpected token "->", expecting identifier or variable" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/18 08:10:44 [error] 32#32: *242 FastCGI sent in stderr: "or "{" or "$"" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/18 08:21:45 [error] 33#33: *325 FastCGI sent in stderr: "PHP message: 2021-08-18T08:21:45+00:00 [critical] Uncaught Error: syntax error, unexpected token "=>", expecting "]"" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/18 13:25:02 [error] 32#32: *1195 FastCGI sent in stderr: "PHP message: 2021-08-18T13:25:02+00:00 [critical] Uncaught Error: syntax error, unexpected token ";", expecting "]"" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/19 09:17:15 [warn] 31#31: *210 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /_profiler/a98fd8?panel=logger HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/19 09:17:31 [warn] 31#31: *213 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/2/00/0000000002 while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /_profiler/a98fd8?panel=exception HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/_profiler/a98fd8?panel=logger"
2021/08/19 09:22:18 [error] 31#31: *244 FastCGI sent in stderr: "PHP message: 2021-08-19T09:22:18+00:00 [critical] Uncaught Error: syntax error, unexpected token "}"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /allprocess HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/19 09:25:35 [warn] 31#31: *283 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/3/00/0000000003 while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /_profiler/765d9a?panel=logger HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/19 09:25:46 [warn] 31#31: *286 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/4/00/0000000004 while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /_profiler/765d9a?panel=exception HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/_profiler/765d9a?panel=logger"
2021/08/19 09:38:49 [error] 31#31: *394 FastCGI sent in stderr: "PHP message: 2021-08-19T09:38:49+00:00 [critical] Uncaught Error: syntax error, unexpected token ":"" while reading upstream, client: 172.18.0.1, server: localhost, request: "POST /allprocess HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/19 09:39:54 [error] 31#31: *398 FastCGI sent in stderr: "PHP message: 2021-08-19T09:39:54+00:00 [critical] Uncaught Error: syntax error, unexpected token "=>", expecting ")"" while reading upstream, client: 172.18.0.1, server: localhost, request: "POST /allprocess HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess"
2021/08/19 11:35:05 [error] 31#31: *831 FastCGI sent in stderr: "PHP message: 2021-08-19T11:35:05+00:00 [critical] Uncaught Error: Unclosed '{' on line 18 does not match ']'" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /allprocess/?s.State.Id=21 HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/allprocess/?s.State.Id=21"
2021/08/19 11:44:01 [error] 31#31: *861 FastCGI sent in stderr: "PHP message: 2021-08-19T11:44:01+00:00 [critical] Uncaught Error: syntax error, unexpected token ")"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /allprocess/%3Fs.State.Id=21 HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/19 11:44:06 [error] 31#31: *861 FastCGI sent in stderr: "PHP message: 2021-08-19T11:44:06+00:00 [critical] Uncaught Error: syntax error, unexpected token ")"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /allprocess/%3Fs.State.Id=21 HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/08/23 12:36:04 [warn] 34#34: *25 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 172.18.0.1, server: localhost, request: "POST /login HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/08/23 12:36:38 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /login HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/08/23 12:36:42 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /login HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/08/23 12:37:57 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "POST /login HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/08/23 12:37:59 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/06 09:06:31 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/06 09:06:31 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/09/06 09:06:32 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/06 09:06:32 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/09/06 09:06:33 [error] 31#31: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/06 09:06:33 [error] 31#31: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/09/06 12:51:07 [error] 31#31: *49 FastCGI sent in stderr: "PHP message: 2021-09-06T12:51:07+00:00 [critical] Uncaught Exception: [Semantical Error] The annotation "@ApiResource" in class App\Entity\Process was never imported. Did you maybe forget to add a "use" statement for this annotation?" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/06 13:08:49 [error] 31#31: *103 FastCGI sent in stderr: "PHP message: 2021-09-06T13:08:49+00:00 [critical] Uncaught Exception: [Semantical Error] The annotation "@ApiResource" in class App\Entity\Contact was never imported. Did you maybe forget to add a "use" statement for this annotation?" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /api/companies?page=1 HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/api"
2021/09/06 13:09:11 [error] 31#31: *105 FastCGI sent in stderr: "PHP message: 2021-09-06T13:09:11+00:00 [critical] Uncaught Exception: [Semantical Error] The annotation "@ApiResource" in class App\Entity\Contact was never imported. Did you maybe forget to add a "use" statement for this annotation?" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/14 11:43:54 [error] 33#33: *1 FastCGI sent in stderr: "PHP message: 2021-09-14T11:43:54+00:00 [critical] Uncaught Error: Class 'Knp\Bundle\PaginatorBundle\KnpPaginatorBundle' not found" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/14 11:43:59 [error] 33#33: *1 FastCGI sent in stderr: "PHP message: 2021-09-14T11:43:59+00:00 [critical] Uncaught Error: Class 'Knp\Bundle\PaginatorBundle\KnpPaginatorBundle' not found" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/14 11:44:06 [error] 33#33: *1 FastCGI sent in stderr: "PHP message: 2021-09-14T11:44:06+00:00 [critical] Uncaught Error: Class 'Knp\Bundle\PaginatorBundle\KnpPaginatorBundle' not found" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/14 11:44:09 [error] 33#33: *1 FastCGI sent in stderr: "PHP message: 2021-09-14T11:44:09+00:00 [critical] Uncaught Error: Class 'Knp\Bundle\PaginatorBundle\KnpPaginatorBundle' not found" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/14 14:32:14 [error] 32#32: *117 FastCGI sent in stderr: "PHP message: 2021-09-14T14:32:14+00:00 [critical] Uncaught Exception: Because you have multiple guard authenticators, you need to set the "guard.entry_point" key to one of your authenticators (App\Security\LoginFormAuthenticator, App\Security\ApiKeyAuthenticator)" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 14:55:33 [error] 32#32: *157 FastCGI sent in stderr: "PHP message: 2021-09-14T14:55:33+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.main.provider". Expected "scalar", but got "array"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 14:55:36 [error] 32#32: *157 FastCGI sent in stderr: "PHP message: 2021-09-14T14:55:36+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.main.provider". Expected "scalar", but got "array"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 14:56:44 [error] 32#32: *160 FastCGI sent in stderr: "PHP message: 2021-09-14T14:56:44+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.main.provider". Expected "scalar", but got "array"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 14:57:41 [error] 32#32: *160 FastCGI sent in stderr: "PHP message: 2021-09-14T14:57:41+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.main.provider". Expected "scalar", but got "array"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 14:57:53 [error] 32#32: *160 FastCGI sent in stderr: "PHP message: 2021-09-14T14:57:53+00:00 [critical] Uncaught Exception: Invalid firewall "main": user provider "app_user_provider | apiKey_user_provider" not found" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 14:58:19 [error] 32#32: *160 FastCGI sent in stderr: "PHP message: 2021-09-14T14:58:19+00:00 [critical] Uncaught Exception: Invalid firewall "main": user provider "app_user_provider apiKey_user_provider" not found" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 14:58:28 [error] 32#32: *160 FastCGI sent in stderr: "PHP message: 2021-09-14T14:58:28+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.main.provider". Expected "scalar", but got "array"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 14:59:14 [error] 32#32: *160 FastCGI sent in stderr: "PHP message: 2021-09-14T14:59:14+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.main.provider". Expected "scalar", but got "array"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 14:59:30 [error] 32#32: *160 FastCGI sent in stderr: "PHP message: 2021-09-14T14:59:30+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.main.provider". Expected "scalar", but got "array"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 15:03:21 [error] 32#32: *168 FastCGI sent in stderr: "PHP message: 2021-09-14T15:03:21+00:00 [critical] Uncaught Exception: Unrecognized option "chain_provider" under "security". Available options are "access_control", "access_decision_manager", "access_denied_url", "always_authenticate_before_granting", "enable_authenticator_manager", "encoders", "erase_credentials", "firewalls", "hide_user_not_found", "password_hashers", "providers", "role_hierarchy", "session_fixation_strategy"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 15:04:43 [error] 32#32: *170 FastCGI sent in stderr: "PHP message: 2021-09-14T15:04:43+00:00 [critical] Uncaught Exception: The file "/var/www/config/packages/security.yaml" does not contain valid YAML: Duplicate key "app_user_provider" detected at line 18 (near "    property: apiToken") in /var/www/config/packages/security.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 15:19:05 [error] 32#32: *200 FastCGI sent in stderr: "PHP message: 2021-09-14T15:19:05+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.api.guard.authenticators". Expected "array", but got "string"
Hint: An array of service ids for all of your "authenticators"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/companies HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 15:19:43 [error] 32#32: *200 FastCGI sent in stderr: "PHP message: 2021-09-14T15:19:43+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.api.guard.authenticators". Expected "array", but got "string"
Hint: An array of service ids for all of your "authenticators"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/companies HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 15:20:01 [error] 32#32: *200 FastCGI sent in stderr: "PHP message: 2021-09-14T15:20:01+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.api.guard.authenticators". Expected "array", but got "string"
Hint: An array of service ids for all of your "authenticators"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/companies HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 15:20:44 [error] 32#32: *200 FastCGI sent in stderr: "PHP message: 2021-09-14T15:20:44+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.api.guard.authenticators". Expected "array", but got "string"
Hint: An array of service ids for all of your "authenticators"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/companies HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/14 15:20:51 [error] 32#32: *200 FastCGI sent in stderr: "PHP message: 2021-09-14T15:20:51+00:00 [critical] Uncaught Exception: Invalid type for path "security.firewalls.api.guard.authenticators". Expected "array", but got "string"
Hint: An array of service ids for all of your "authenticators"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/companies HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/09/16 09:31:59 [emerg] 1#1: host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/default.conf:2
2021/09/16 09:59:18 [error] 35#35: *21 FastCGI sent in stderr: "PHP message: 2021-09-16T09:59:18+00:00 [critical] Uncaught Error: syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ')'" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /user HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/account/"
2021/09/23 14:43:00 [error] 35#35: *1366 FastCGI sent in stderr: "PHP message: 2021-09-23T14:43:00+00:00 [critical] Uncaught Error: syntax error, unexpected ''entry_options'' (T_CONSTANT_ENCAPSED_STRING), expecting ']'" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /companies/6/edit HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/companies/"
2021/09/23 15:53:09 [error] 35#35: *1910 FastCGI sent in stderr: "PHP message: 2021-09-23T15:53:09+00:00 [critical] Uncaught Exception: Class "App\EventSubscriber\LocaleSubscriber" used for service "App\EventSubscriber\LocaleSubscriber" cannot be found" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /companies/ HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/user/"
2021/09/23 16:00:39 [error] 35#35: *1988 FastCGI sent in stderr: "PHP message: 2021-09-23T16:00:39+00:00 [critical] Uncaught Error: Argument 4 passed to Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension::registerTranslatorConfiguration() must be of the type string, null given, called in /var/www/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php on line 413" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /companies/ HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/companies/6/edit"
2021/09/23 16:10:42 [error] 35#35: *2275 FastCGI sent in stderr: "PHP message: 2021-09-23T16:10:42+00:00 [critical] Uncaught Error: syntax error, unexpected ';', expecting ')'" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /companies/ HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/09/23 16:15:51 [error] 35#35: *2297 FastCGI sent in stderr: "PHP message: 2021-09-23T16:15:51+00:00 [critical] Uncaught Exception: Invalid type for path "framework.default_locale". Expected "scalar", but got "array"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /companies/ HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/09/23 16:16:23 [error] 35#35: *2297 FastCGI sent in stderr: "PHP message: 2021-09-23T16:16:23+00:00 [critical] Uncaught Exception: Invalid type for path "framework.default_locale". Expected "scalar", but got "array"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /companies/ HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/09/23 16:16:31 [error] 35#35: *2297 FastCGI sent in stderr: "PHP message: 2021-09-23T16:16:31+00:00 [critical] Uncaught Error: Argument 4 passed to Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension::registerTranslatorConfiguration() must be of the type string, null given, called in /var/www/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php on line 413" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /companies/ HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/09/27 16:13:27 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/09/27 18:51:50 [error] 34#34: *1280 FastCGI sent in stderr: "PHP message: 2021-09-27T18:51:50+00:00 [critical] Uncaught Error: syntax error, unexpected ')', expecting ']'" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /user/ HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/user/10/edit"
2021/09/27 18:57:05 [error] 34#34: *1451 FastCGI sent in stderr: "PHP message: 2021-09-27T18:57:05+00:00 [critical] Uncaught Error: syntax error, unexpected '$request' (T_VARIABLE)" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /user/ HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/user/10/edit"
2021/09/27 20:37:08 [error] 34#34: *2181 FastCGI sent in stderr: "PHP message: 2021-09-27T20:37:08+00:00 [critical] Uncaught Error: syntax error, unexpected 'dashboard' (T_STRING), expecting ')'" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/account/"
2021/09/30 12:40:51 [error] 36#36: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:40:52 [error] 36#36: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:46:36 [error] 33#33: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:38 [error] 33#33: *8 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:38+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:57 [error] 33#33: *10 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:57+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:57 [error] 33#33: *12 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:57+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:57 [error] 33#33: *14 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:57+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:58 [error] 33#33: *16 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:58+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:58 [error] 33#33: *18 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:58+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:58 [error] 33#33: *20 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:58+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:58 [error] 33#33: *22 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:58+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:58 [error] 33#33: *24 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:58+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:46:58 [error] 30#30: *26 FastCGI sent in stderr: "PHP message: 2021-09-30T12:46:58+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:48:43 [error] 35#35: *1 FastCGI sent in stderr: "PHP message: 2021-09-30T12:48:43+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:49:24 [error] 35#35: *1 FastCGI sent in stderr: "PHP message: 2021-09-30T12:49:24+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:50:02 [error] 35#35: *4 FastCGI sent in stderr: "PHP message: 2021-09-30T12:50:02+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:50:03 [error] 35#35: *6 FastCGI sent in stderr: "PHP message: 2021-09-30T12:50:03+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:50:03 [error] 35#35: *8 FastCGI sent in stderr: "PHP message: 2021-09-30T12:50:03+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:50:03 [error] 35#35: *10 FastCGI sent in stderr: "PHP message: 2021-09-30T12:50:03+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:50:03 [error] 36#36: *12 FastCGI sent in stderr: "PHP message: 2021-09-30T12:50:03+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:50:03 [error] 35#35: *14 FastCGI sent in stderr: "PHP message: 2021-09-30T12:50:03+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:50:04 [error] 35#35: *16 FastCGI sent in stderr: "PHP message: 2021-09-30T12:50:04+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:50:04 [error] 35#35: *18 FastCGI sent in stderr: "PHP message: 2021-09-30T12:50:04+00:00 [critical] Uncaught Exception: Invalid environment provided to "App\Kernel": the environment cannot be empty" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:54:46 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:54:46 [error] 34#34: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/09/30 12:54:47 [error] 34#34: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:54:48 [error] 34#34: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/dashboard"
2021/09/30 12:54:50 [error] 34#34: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:54:51 [error] 34#34: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:54:52 [error] 34#34: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:54:52 [error] 34#34: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:54:52 [error] 34#34: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:54:52 [error] 34#34: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:54:52 [error] 34#34: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:54:59 [error] 34#34: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:55:00 [error] 34#34: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:55:00 [error] 34#34: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:55:01 [error] 34#34: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:55:01 [error] 34#34: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:55:01 [error] 34#34: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:55:01 [error] 34#34: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 12:55:01 [error] 34#34: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /login HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 12:55:01 [error] 34#34: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/login"
2021/09/30 13:04:02 [error] 35#35: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 13:04:02 [error] 35#35: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/09/30 13:04:04 [error] 35#35: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 13:04:04 [error] 35#35: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/09/30 13:04:08 [error] 35#35: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 13:04:09 [error] 35#35: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 13:04:09 [error] 35#35: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/09/30 13:04:10 [error] 35#35: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 13:04:10 [error] 35#35: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 13:04:10 [error] 35#35: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 13:04:10 [error] 35#35: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/09/30 13:04:10 [error] 35#35: *20 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 13:04:10 [error] 35#35: *20 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/09/30 13:04:10 [error] 33#33: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/09/30 13:04:10 [error] 33#33: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/21 08:11:58 [error] 36#36: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/10/21 08:11:58 [error] 36#36: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/21 08:12:00 [error] 36#36: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
